package main

import "fmt"

func main() {
	var n int
	fmt.Scan(&n)

	count := 0
	for _, cnt := range PrimeFactorize(n) {
		for i := 1; i <= cnt; i++ {
			count++
			cnt -= i
		}
	}

	fmt.Println(count)
}

// generated by https://github.com/murosan/gollect

func PrimeFactorize(n int) map[int]int {
	m := make(map[int]int)
	for n%2 == 0 {
		m[2]++
		n /= 2
	}
	for i := 3; i*i <= n; i += 2 {
		for n%i == 0 {
			m[i]++
			n /= i
		}
	}
	if n != 1 {
		m[n]++
	}
	return m
}
