# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-05-05
# ABC096 C
# Your code here
$h, $w = gets.chomp.split(' ').map(&:to_i)

$c = []
$h.times do
  $c << gets.chomp.split('')
end

$h.times do |i|
  $w.times do |j|
    next if $c[i][j] == '.'
    $stuck = [[i, j]]
    count = 0

    until $stuck.empty?
      y, x = $stuck.pop

      next if $c[y][x] == '.'

      count += 1

      $c[y][x] = '.'

      $stuck << [y - 1, x] if y - 1 >= 0
      $stuck << [y + 1, x] if y + 1 < $h
      $stuck << [y, x + 1] if x + 1 < $w
      $stuck << [y, x - 1] if x - 1 >= 0
    end

    if count == 1
      puts 'No'
      exit(0)
    end
  end
end

puts 'Yes'
