# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-05-05
# ABC096 B
# Your code here
$a, $b, $c = gets.chomp.split(' ').map(&:to_i)
$K = gets.chomp.to_i

k = 2**$K

puts [$a, $b, $c].reduce(:+) + [$a, $b, $c].max * k - [$a, $b, $c].max
