package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
)

func main() {
	sc := NewScanner(os.Stdin)
	a := ParseInt64(sc.Bytes())
	b := ParseInt64(sc.Bytes())
	fmt.Println(a * b / 100)
}

func ParseInt64(b []byte) (n int64) {
	var i int
	if b[0] == '-' {
		i++
	}
	for ; i < len(b); i++ {
		if '0' <= b[i] && b[i] <= '9' {
			n *= 10
			n += int64(b[i] - '0')
		}
	}
	if b[0] == '-' {
		return -n
	}
	return
}

// generated by https://github.com/murosan/gollect

type Scanner struct{ *bufio.Scanner }

func NewScanner(r io.Reader) *Scanner {
	s := bufio.NewScanner(r)
	s.Split(bufio.ScanWords)
	return &Scanner{Scanner: s}
}

func (s *Scanner) Bytes() []byte { s.Scan(); return s.Scanner.Bytes() }
